### ISSUE TITLE
🪲Bug: Ibus not working with inverted RX on RP2040 Microcontroller

### ISSUE THREAD

**Issue by gandy92** [Witty-Wizard/SerialIO#26]
**Describe the bug**
Using the ```ibus``` receiver class with an inverted line connected to a RP2040 mcu only yields 0 for all channels. The reason being that the ```ibus.setup()``` routine has architecture dependent code which does not honor the ```ibus._inverted flag```. 

A valid workaround is to add the inverting calls to the main sketch:
```c++
ibus receiver(&Serial1, SBUS_RX_PIN, SBUS_TX_PIN, true);  // RP2040 requires a TX_PIN so to not hang up the mcu
void setup()
{
  Serial1.setInvertRX(true);
  Serial1.setInvertTX(true);
  receiver.begin();
```

**To Reproduce**
I can try to provide an example sketch that demonstrates using the ibus protocol with the rp2040, if this is required. 

**Additional context**
The problematic code can be seen in this line:
https://github.com/Witty-Wizard/SerialIO/blob/b97e68feb2dc759e38fe85af2853a2db5ec2e31e/src/ibus/ibus.cpp#L18

The issue is resolved by adding two lines with calls to ```serialPort->setInvertRC()``` and ```serialPort->setInvertTX()``` before ```serialPort->begin()```, changing the code to:
```c++
#elif defined(ARDUINO_ARCH_RP2040)
  SerialUART *serialPort = (SerialUART *)_rxPort;
  serialPort->setPinout(_txPin, _rxPin);
  serialPort->setInvertRX(_inverted);
  serialPort->setInvertTX(_inverted);
  serialPort->begin(IBUS_BAUDRATE, SERIAL_8N1);
#else

```

**Comment by Witty-Wizard** [comment]
@gandy92, Thank your bringing this to my notice.
I didn't knew the `RP2040` Microcontroller supported `UART` inversion, I have made these changes in the #27 PR, please try the new branch and share the results so that I can merge the code into the main branch

**Comment by gandy92** [comment]
@Witty-Wizard thank you for your prompt reaction. Now that you mention it, I'm not using the vanilla RP2040 arduino framework but the work from https://github.com/earlephilhower/arduino-pico which adds a ton more features. I'll try to check if the pin inversion is also available in the vanilla code or is part of these additional features.

**Comment by gandy92** [comment]
@Witty-Wizard I ran a quick check and as it turns out, I can not compile SerialIO with the vanilla raspberrypi platform, where SerialUART seems to be unknown. So maybe the RP2040-related code already relies on the earlephilhower core? If so, may I suggest adding it to the documentation somewhere? 
If you like, I can try to create a minimal sketch showing how to set up ibus with therp2040 to be included with the examples? Would you prefer a PR for that or should I just paste the code here?

**Comment by Witty-Wizard** [comment]
Sure it would be great if u could create an example sketch, and add doxygen style comments to it, then it will be automatically included in the documentation.

**Comment by gandy92** [comment]
Ok, I'll check out the other examples to adhere to the same scheme
