### ISSUE TITLE
✨FEATURE: Allow to get 16-bit ibus channel data

### ISSUE THREAD

**Issue by gandy92** [Witty-Wizard/SerialIO#28]
**Is your feature request related to a problem? Please describe.**
The FlySky receiver FS-IA6B outputs 16-bit channel data on the IBUS, which are available through ```ibus::getChannel(rc_channels_t *channelData)```.  This being 11-bit data works fine as long as the data stays in the usual range of values from 1000 through to 2000.

However, an RC control can be tuned to output a larger range of values, e.g. 906 to 1058, which leads to an overflow in the ```rc_channel_t``` channel values, resulting values above 1047 to be wrapped to values starting with 0. 

**Describe the solution you'd like**
One way to solve the issue would be to add a second ```getChannel()``` method, allowing the user to alternatively get the 16-bit channel data:
```c++
void ibus::getChannel(ibus_channels_t *channelData) {
  memcpy(channelData, (uint8_t *)&_channelData, sizeof(ibus_channels_t));
}
```

**Describe alternatives you've considered**
A workaround exists on the application level where each channel value 0..499 is wrapped to values 1048..1547, expecting that no receiver outputs values below 500.

**Comment by Witty-Wizard** [comment]
@gandy92 ,
My understanding is 11-bits give a range of 0-2048, which should be enough for standard packets, but having 16-bits of data packets is a more robust solution.

**Comment by gandy92** [comment]
@Witty-Wizard , definitely an edge case - until I've seen those values wrapping around, I had assumed the same.

**Comment by Witty-Wizard** [comment]
@gandy92, I have created a new [branch](https://github.com/Witty-Wizard/SerialIO/tree/28-feature-allow-to-get-16-bit-ibus-channel-data), for this issue

**Comment by Witty-Wizard** [comment]
@gandy92, I have created a PR #32 for this issue, please check that and share your thoughts, also I have made the method available from the `SerialIO` class, not the best solution but it should work

**Comment by Witty-Wizard** [comment]
@gandy92, The reason to use 11bit channels in the first place was because protocols like `Sbus` and `crsf` transmit in 11 bits so it is easier to decode by just `memcpying` the buffer to the target `structure`

As shown in [here](https://github.com/Witty-Wizard/SerialIO/blob/a4ef18e8bb832dd7db4e5d4983a8ff2bf1f236a2/src/sbus/sbus.cpp#L33)

**Comment by gandy92** [comment]
@Witty-Wizard , I see - and makes perfect sense, too. I'm afraid I don't see an obvious solution to this, other than what you have implemented already.

**Comment by Witty-Wizard** [comment]
@gandy92, Well if the solution works i think it is good enough. I am going to merge it into the main branch
